export {
  db,
  type Playlist,
  type MediaKind,
  type M3UItem,
  type M3UGroup,
  type Favorite,
  type WatchProgress,
  getPlaylistItems,
  getPlaylistGroups,
  getItemsByGroup,
  addFavorite,
  removeFavorite,
  isFavorite,
  updateWatchProgress,
  getWatchProgress,
  getContinueWatching,
  clearPlaylistData,
  removePlaylistWithData,
} from './schema';

export {
  addPlaylist,
  refreshPlaylist,
  getAllPlaylists,
  getActivePlaylist,
  setActivePlaylist,
  removePlaylist,
  getActivePlaylistStats,
} from './operations';
